<?php
// $Id$

/**
 * @file
 * StyleWriter
 */

module_load_include('inc', 'stylewriter', 'stylewriter');

/**
 * Implementation of hook_menu()
 */
function stylewriter_menu() {
  $items = array();

  // Core OpenLayers settings pages.
  $items['admin/settings/stylewriter'] = array(
    'title' => 'StyleWriter',
    'description' => 'StyleWriter server and cache management.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stylewriter_settings'),
    'access arguments' => array('administer stylewriter'),
    'file' => 'includes/stylewriter.admin.inc',
    'type' => MENU_NORMAL_ITEM
  );

  $items['admin/settings/stylewriter/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -20,
  );

  // Core OpenLayers settings pages.
  $items['admin/settings/stylewriter/cache'] = array(
    'title' => 'Cache',
    'description' => 'StyleWriter server and cache management.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stylewriter_cache_form'),
    'access arguments' => array('administer stylewriter'),
    'file' => 'includes/stylewriter.admin.inc',
    'type' => MENU_LOCAL_TASK
  );
  return $items;
}

/**
 * Implementation of hook_views_api().
 */
function stylewriter_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'stylewriter') .'/views',
  );
}

/**
 * Implementation of hook_ctools_plugin_api().
 */
function stylewriter_ctools_plugin_api($module, $api) {
  if ($module == "openlayers") {
    switch ($api) {
      case 'openlayers_layers':
        return array('version' => 1);
    }
  }
}


/**
 * Implementation of hook_theme().
 */
function stylewriter_theme() {
  $path = drupal_get_path('module', 'stylewriter');
  return array(
    'stylewriter_rule' => array(
      'arguments' => array(
        'filter' => '',
        'polygon' => array(),
        'stroke' => array(),
        'metawriter' => array(),
        'point' => array(),
        'marker' => array(),
      ),
      'file' => 'stylewriter.theme.inc',
      'template' => 'stylewriter-rule',
      'path' => $path . "/views",
    ),
    'stylewriter_swatch' => array(
      'arguments' => array(
        'color' => '',
        'dist' => '',
      ),
      'file' => 'stylewriter.theme.inc',
      'template' => 'stylewriter-swatch',
      'path' => $path . "/views",
    ),
    'stylewriter_document' => array(
      'arguments' => array(
        'rules' => '',
        'data_url' => '',
        'data_type' => 'shape',
        'metawriter' => FALSE,
        'layer' => FALSE
      ),
      'file' => 'stylewriter.theme.inc',
      'template' => 'stylewriter-document',
      'path' => $path . "/views",
    ),
    'stylewriter_legend' => array(
      'arguments' => array(
        'swatches' => '',
        'value_min' => '',
        'value_max' => '',
        'label' => '',
      ),
      'file' => 'stylewriter.theme.inc',
      'template' => 'stylewriter-legend',
      'path' => $path . "/views",
    ),
  );
}

/**
 * Implementation of openlayers_layer_type
 */
function stylewriter_openlayers_layer_types() {
  return array(
    'openlayers_layer_type_stylewriter' => array(
      'title' => t('Stylewriter'),
      'description' => t('Stylewriter Dynamic Maps'),
      'type' => 'layer',
      'path' => drupal_get_path('module', 'stylewriter') .'/includes/layer_types',
      'file' => 'stylewriter.inc',
      'layer_type' => array(
        'class' => 'openlayers_layer_type_stylewriter',
        'parent' => 'openlayers_layer_type',
      ),
    ),
    /*
    'openlayers_layer_type_stylewriter_interaction' => array(
      'title' => t('Stylewriter Interaction'),
      'description' => t('Stylewriter Dynamic Map Interaction'),
      'type' => 'layer',
      'path' => drupal_get_path('module', 'stylewriter') .'/includes/layer_types',
      'file' => 'stylewriter_interaction.inc',
      'layer_type' => array(
        'class' => 'openlayers_layer_type_stylewriter_interaction',
        'parent' => 'openlayers_layer_type',
      ),
    ),
     */
  );
}

/**
 * Implementation of hook_openlayers_behaviors().
 *
 * This is a ctools plugins hook.
 */
function stylewriter_openlayers_behaviors() {
  return array(
    'stylewriter_pointhover' => array(
      'title' => t('StyleWriter PointHover'),
      'behavior' => array(
        'path' => drupal_get_path('module', 'stylewriter') .'/includes/behaviors',
        'file' => 'stylewriter_pointhover.inc',
        'class' => 'stylewriter_pointhover',
        'parent' => 'openlayers_behavior',
      ),
    ),
  );
}
